tribetactics/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Length, Email, ValidationError
from tribetactics.models import Restaurant

class RestaurantForm(FlaskForm):
    name = StringField('name',
                        validators=[DataRequired(), Length(min=2, max=20)])
    submit = SubmitField('Create Restaurant')

    def validate_name(self, name):
        restaurant = Restaurant.query.filter_by(name=name.data).first()
        if restaurant:
            raise ValidationError('That name is taken. Please choose another one')


class ItemForm(FlaskForm):
    name = StringField('name',
                        validators=[DataRequired(), Length(min=2, max=20)])
    price = IntegerField('price',
                        validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_name(self, name):
        restaurant = Restaurant.query.filter_by(name=name.data).first()
        if restaurant:
            raise ValidationError('That name is taken. Please choose another one')

tribetactics/dashboard/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from tribetactics.users.utils import admin_required, restaurant_required
from tribetactics.dashboard.forms import RestaurantForm, ItemForm
from tribetactics.models import Item, Restaurant, Menu, Order
from tribetactics import db

dashboard = Blueprint('dashboard', __name__)


@dashboard.route('/dashboard/')
@login_required
@restaurant_required
def restaurant_dash():
    return render_template('dashboard.html')


@dashboard.route('/dashboard/createRestaurant/', methods=['GET', 'POST'])
@login_required
@restaurant_required
def create_restaurant():
    form = RestaurantForm()
    if form.validate_on_submit():
        restaurant = Restaurant(name=form.name.data,
                    owner_id=current_user.id)
        db.session.add(restaurant)
        db.session.commit()
        menu = Menu(name=restaurant.name,
                    restaurant_id=restaurant.id)
        db.session.add(menu)
        db.session.commit()
        flash(f'Your account has been created', 'success')
        return redirect(url_for('dashboard.restaurant_dash'))
    return render_template('createRestaurant.html', title='Create Restaurant', form=form)

    
@dashboard.route('/dashboard/<int:id>/createItem/', methods=['GET', 'POST'])
@login_required
@restaurant_required
def create_item(id):
    form = ItemForm()
    item = Item.query.filter_by(name=form.name.data).first()
    if item != None:
        flash(f'This item name is taken before. Choose another one!', 'danger')
        return redirect(url_for('dashboard.restaurant_dash'))
    if form.validate_on_submit():
        item = Item(name=form.name.data,
                    price=form.price.data,
                    menu_id=id)
        db.session.add(item)
        db.session.commit()
        
        flash(f'Your item has been added!', 'success')
        return redirect(url_for('dashboard.restaurant_dash'))
    return render_template('createItem.html', title='Create Item', form=form)


@dashboard.route('/dashboard/editItem/<int:item_id>/', methods=['GET', 'POST'])
@login_required
@restaurant_required
def edit_item(item_id):
    form = ItemForm()
    item = Item.query.get(item_id)
    if item == None:
        flash(f'You entered wrong Item ID!', 'danger')
        return redirect(url_for('dashboard.restaurant_dash'))
    if form.validate_on_submit():
        item.name = form.name.data
        item.price = form.price.data
        db.session.commit()
        flash(f'Your item has been updated!', 'success')
        return redirect(url_for('dashboard.restaurant_dash'))
    return render_template('editItem.html', title='Edit Item', form=form, item=item)


@dashboard.route('/dashboard/deleteItem/<int:item_id>/')
@login_required
@restaurant_required
def delete_item(item_id):
    item = Item.query.get(item_id)
    if item == None:
        flash(f'this Item is not found', 'danger')
        return redirect(url_for('dashboard.restaurant_dash'))
    
    # print(item.orders[0].order.status)
    for itemOrder in item.orders:
        if itemOrder.order.status == 'Pending':
            flash(f'this Item is still in a pending order', 'danger')
            return redirect(url_for('dashboard.restaurant_dash'))
    db.session.delete(item)
    db.session.commit()
    flash(f'Your item has been deleted!', 'success')
    return redirect(url_for('dashboard.restaurant_dash'))


@dashboard.route('/dashboard/deleverOrder/<int:order_id>/')
@login_required
@restaurant_required
def deliver_order(order_id):
    order = Order.query.get(order_id)
    if order == None:
        flash(f'this order is not found', 'danger')
        return redirect(url_for('dashboard.restaurant_dash'))
    order.status = 'Delivered'
    db.session.commit()
    flash(f'Your order status has been updated!', 'success')
    return redirect(url_for('dashboard.restaurant_dash'))

tribetactics/main/routes.py
from flask import Blueprint, render_template, send_from_directory
from flask_login import login_required
from tribetactics.users.utils import admin_required, restaurant_required


main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html')

@main.route('/static/<path:path>')
def send_static(path):
    return send_from_directory('static', path)

tribetactics/users/routes.py
from operator import ne
from flask import Blueprint, render_template, flash, redirect, request
from flask.helpers import url_for
from .forms import RegistrationForm, LoginForm
from tribetactics import db, bcrypt
from tribetactics.models import User, Role
from flask_login import login_user, current_user, logout_user
from tribetactics import limiter


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        role = Role.query.get(form.account_type.data)
        user.roles.append(role)
        db.session.commit()
        flash(f'Your account has been created', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    return render_template('login.html', title='Login', form=form)


@users.route('/login', methods=['POST'])
@limiter.limit("3/5minute")
def login_post():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessfull. Please check your email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.errorhandler(429)
def ratelimit_handler(e):
    flash('Too Many Requests. Please Make a new login request after 5 minutes', 'danger')
    return redirect(url_for('users.login'))

tribetactics/templates/createItem.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=''>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Item</legend>
                <div class="form-group">
                    {{ form.name.label(class='form-control-label') }}
                    {% if form.name.errors %}
                        {{ form.name(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.price.label(class='form-control-label') }}
                    {% if form.price.errors %}
                        {{ form.price(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.price.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.price(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

tribetactics/templates/createRestaurant.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=''>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Restaurant</legend>
                <div class="form-group">
                    {{ form.name.label(class='form-control-label') }}
                    {% if form.name.errors %}
                        {{ form.name(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

tribetactics/templates/dashboard.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    {% if current_user.restaurants|length == 0 %}
    <div class="text-center"> <!--// child#1 //-->
        <h3 class="text-center mt-2">It seems that, you don't have any restaurants yet!</h3>
        <br>
        <a class="btn btn-outline-info mb-2" href='{{ url_for('dashboard.create_restaurant')}}'>Register a new restaurant</a>
    </div> <!--// close of content section child#1 //-->
    {% else %}
    <div class="row"> <!--// child#2 //-->
        <div class="col-md-12">
            <h3 class="float-left mt-2 col-md-8">Restaurants</h3>
            <a class=" float-right btn btn-outline-success mt-2" href='{{ url_for('dashboard.create_restaurant')}}'>+ new restaurant</a>
        </div>
    </div> <!--// close of content section child#2 //-->
    <br>
    <div class="col-md-12"> <!--// child#3 //-->
        {% for restaurant in current_user.restaurants %}
        <div id="accordion"> <!--// accordion //-->
            <div class="card"> <!--// card //-->
                <div class="card-header" id="headingOne"> <!--// card header //-->
                    <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#{{restaurant.name}}" aria-expanded="true" aria-controls="collapseOne">
                        <h5>{{ restaurant.name }}</h5>
                    </button>
                    </h5>
                </div> <!--// close of card header //-->
                <div id="{{restaurant.name}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordion"> <!--// card body //-->
                    <div class="card-body"> <!--// card body //-->
                        {% if not restaurant.menu %}
                        <div class="text-center">
                            <h6 class="text-center mt-1">It seems that, you don't have any items in your menu!</h6>
                            <br>
                            <a class="btn btn-outline-info mb-1" href='{{ url_for('dashboard.create_item', id=restaurant.menu.id)}}'>+ Add new Item</a>
                        </div>
                        {% else %}
                        <ul class="nav nav-tabs" id="{{restaurant.name}}Tab" role="tablist">
                            <li class="nav-item">
                            <a class="nav-link active" id="{{restaurant.name}}Menu-tab" data-toggle="tab" href="#{{restaurant.name}}Menu" role="tab">Menu</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" id="{{restaurant.name}}Order-tab" data-toggle="tab" href="#{{restaurant.name}}Order" role="tab">Orders</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="{{restaurant.name}}TabContent"><!--// tap content //-->
                            <div class="tab-pane fade show active" id="{{restaurant.name}}Menu" role="tabpanel"><!--// Menu tab content //-->
                                <!-- ITEMS page  -->
                                <div class="row"><!-- ITEMS page row -->
                                    <div class="col-md-12">
                                        <h3 class="float-left mt-2 col-md-8">Menu</h3>
                                        <a class=" float-right btn btn-outline-success mt-2" href='{{ url_for('dashboard.create_item', id=restaurant.menu.id)}}'>+ new Item</a>
                                    </div>

                                    <div class="col-md-12">
                                        {% if not restaurant.menu.items %}
                                        <div class="text-center">
                                            <h6 class="text-center mt-1">It seems that, you don't have any items yet! add some!!</h6>
                                        </div>
                                        {% else %}
                                        <table class="table table-striped table-hover">
                                            <thead>
                                                <tr>
                                                    <th style="width: 15%" scope="col">#</th>
                                                    <th style="width: 30%" scope="col">name</th>
                                                    <th style="width: 30%" scope="col">price</th>
                                                    <th style="width: 25%" scope="col"></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in restaurant.menu.items %}
                                                <tr>
                                                    <th scope="row">{{restaurant.menu.items.index(item)}}</th>
                                                    <td>{{item.name}}</td>
                                                    <td>{{item.price}} $</td>
                                                    <td class="text-right">
                                                        <a class="btn btn-outline-info" href='{{ url_for('dashboard.edit_item', item_id=item.id)}}'>🔧 Edit</a>
                                                        <a class="btn btn-outline-danger" href='{{ url_for('dashboard.delete_item', item_id=item.id)}}'>🗑️ Delete</a>
                                                    </td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        {% endif %}
                                    </div>


                                </div>
                            </div><!--// close of Menu tap content //-->
                            <div class="tab-pane fade" id="{{restaurant.name}}Order" role="tabpanel"><!--// Order tap content //-->
                                <!-- ORDERS page  -->
                            <div class="row">
                                <div class="col-md-12">
                                    <h3 class="float-left mt-2 col-md-8">Orders</h3>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th style="width: 15%" scope="col">#</th>
                                            <th style="width: 30%" scope="col">Order_id</th>
                                            <th style="width: 30%" scope="col">Status</th>
                                            <th style="width: 25%" scope="col"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for order in restaurant.orders %}
                                            <tr>
                                                <th scope="row">{{restaurant.orders.index(order)}}</th>
                                                <td>{{order.id}}</td>
                                                <td>{{order.status}}</td>
                                                {% if order.status == 'Pending' %}
                                                <td class="text-right">
                                                    <a class="btn btn-outline-info" href='{{ url_for('dashboard.deliver_order', order_id=order.id)}}'>✔️ Mark as Delivered</a>
                                                </td>
                                                {% else %}
                                                <td></td>
                                                {% endif %}
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div> <!--// close of Order tap content //-->
                        </div><!--// close of tab content //-->
                        {% endif %}
                    </div><!--// close of card body //-->
                </div><!--// close of card body //-->
            </div><!--// close of card //-->
        </div> <!--// close of accordion //-->
        {% endfor %}
    </div> <!--// close of content section child#3 //-->
    {% endif %}
</div> <!--// close of content section //-->
{% endblock content %}

tribetactics/templates/editItem.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=''>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Item</legend>
                <div class="form-group">
                    {{ form.name.label(class='form-control-label') }}
                    {% if form.name.errors %}
                        {{ form.name(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class='form-control form-control-lg', value=item.name) }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.price.label(class='form-control-label') }}
                    {% if form.price.errors %}
                        {{ form.price(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.price.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.price(class='form-control form-control-lg', value=item.price) }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

tribetactics/templates/home.html
{% extends 'layout.html' %}
{% block content %}
<h4>Notes:</h4>
<ul>
    <li><h5>Only Admin and Restaurant owners can access dashboard.</h5></li>
    <li><h5>User can only do limited things via API only </h5></li>
    <li><h5><a href="https://github.com/KhaledM0hamed/Tribetactics">REPOSITORY LINK</a></h5></li>
</ul>
<img src="https://i.ibb.co/WfWLkpK/Flowchart.png" style="width: 100%;">
{% endblock content%}

tribetactics/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Tribetactics - {{ title }}</title>
    {% else %}
        <title>Tribetactics</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Tribetactics</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('dashboard.restaurant_dash') }}">Dashboard</a>
              <a class="nav-item nav-link" href="/swagger">Swagger</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}

                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              
              {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="col-md-8 ml-auto mr-auto">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

tribetactics/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action='{{ url_for('users.login_post')}}'>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <h6>you can copy this cardinals too login</h6>
                <h6>email:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;khaled.zakaria987@gmail.com</h6>
                <h6>password:&nbsp;&nbsp;&nbsp;&nbsp;Khaled123</h6>
                <hr>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small>
            Didn't Have an account yet? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a> 
        </small>
    </div>
{% endblock content %}

tribetactics/templates/register.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action=''>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register</legend>
                <div class="form-group">
                    {{ form.username.label(class='form-control-label') }}
                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class='form-control-label') }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.account_type.label(class='form-control-label') }}
                    {% if form.account_type.errors %}
                        {{ form.account_type(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
                            {% for error in form.account_type.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.account_type(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small>
            Already Have account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a> 
        </small>
    </div>
{% endblock content %}